services:
  backend:
    build:
      context: ./back-end
    volumes:
      - ./back-end:/app
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    networks:
      - my_network

  frontend:
    build:
      context: ./front-end
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - my_network

networks:
  my_network:
    driver: bridge